<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Person', 'doctrine');

/**
 * BasePerson
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_person
 * @property string $user
 * @property string $pass
 * @property string $tip
 * @property Doctrine_Collection $Applications
 * @property Cv $Cv
 * 
 * @method integer             getIdPerson()     Returns the current record's "id_person" value
 * @method string              getUser()         Returns the current record's "user" value
 * @method string              getPass()         Returns the current record's "pass" value
 * @method string              getTip()          Returns the current record's "tip" value
 * @method Doctrine_Collection getApplications() Returns the current record's "Applications" collection
 * @method Cv                  getCv()           Returns the current record's "Cv" value
 * @method Person              setIdPerson()     Sets the current record's "id_person" value
 * @method Person              setUser()         Sets the current record's "user" value
 * @method Person              setPass()         Sets the current record's "pass" value
 * @method Person              setTip()          Sets the current record's "tip" value
 * @method Person              setApplications() Sets the current record's "Applications" collection
 * @method Person              setCv()           Sets the current record's "Cv" value
 * 
 * @package    newproject
 * @subpackage model
 * @author     Alina Parascan
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasePerson extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('person');
        $this->hasColumn('id_person', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('user', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '30',
             ));
        $this->hasColumn('pass', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '30',
             ));
        $this->hasColumn('tip', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '30',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Applications', array(
             'local' => 'id_person',
             'foreign' => 'id_person'));

        $this->hasOne('Cv', array(
             'local' => 'id_person',
             'foreign' => 'id_person'));
    }
}