<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/10/22 23:22:15

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=newproject',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
