<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/11/10 16:05:45

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=recrutare',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
