Applications:
  connection: doctrine
  tableName: applications
  columns:
    id_person:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    id_jobs:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
  relations:
    Person:
      local: id_person
      foreign: id_person
      type: one
    Jobs:
      local: id_jobs
      foreign: id_jobs
      type: one
Cv:
  connection: doctrine
  tableName: cv
  columns:
    id_cv:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    id_person:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    name:
      type: string(30)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    surname:
      type: string(30)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    city:
      type: string(30)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    email:
      type: string(60)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    phone:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    title:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    years_experience:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    description_experience:
      type: string(500)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    education:
      type: string(200)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Person:
      local: id_person
      foreign: id_person
      type: one
      foreignType: one
Jobs:
  connection: doctrine
  tableName: jobs
  columns:
    id_jobs:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    job_title:
      type: string(30)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    posting_date:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    job_description:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    job_location:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Applications:
      local: id_jobs
      foreign: id_jobs
      type: many
Person:
  connection: doctrine
  tableName: person
  columns:
    id_person:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    user:
      type: string(30)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    pass:
      type: string(30)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    tip:
      type: string(30)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Applications:
      local: id_person
      foreign: id_person
      type: many
    Cv:
      local: id_person
      foreign: id_person
      type: one
      foreignType: one
